### ISSUE TITLE
`ingredients` instead of `ceterisParibus2`

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/localModel#16]
@mstaniak what about using `ingredients` instead of `ceterisParibus2` ?
It should be 100% compatibile and is more mature so will get CRAN sooner.

**Comment by mstaniak** [comment]
nice idea, i was going to make a branch with dependency on ceterisParibus instead of ceterisParibus and send to CRAN, changing to ingredients sound better, I'll look into it and do it soon

**Comment by mstaniak** [comment]
okay, I get the ingredients package now, I'm just waiting til it goes to cran.

**Comment by mstaniak** [comment]
Done
