### ISSUE TITLE
Refactoring of individual_surrogate_model

### ISSUE THREAD

**Issue by harell** [ModelOriented/localModel#20]
Thanks for the effort put in this package.

I'm getting an error from individual_surrogate_model line 158

After spending 3 hours debugging this, it doesn't look like I'm having progress.

The main reason is the complexity of individual_surrogate_model.

What does the function in lines 160-179 suppose to do? 

Could you please refactor it into a stand-alone function and add a unit test for easier dubbing?
Moreover, individual_surrogate_model does many things. This makes it hard to (a) understand 
and (b) test isolate cases.

Thanks

![image](https://user-images.githubusercontent.com/7226303/56172221-8825e580-603c-11e9-9faa-6987e1e86e81.png)

**Comment by mstaniak** [comment]
Good point, I will fix this as soon as I can.

The code in lines 160-179 transforms the dataset back to the original data spaces

**Comment by mstaniak** [comment]
Can you please share the error message?  Also, a reproducible example would be nice.

**Comment by harell** [comment]
Sure

Attached is the dataset
Attached is the code. Change line 7 to point at the dataset

[reproducible-bug.zip](https://github.com/ModelOriented/localModel/files/3086991/reproducible-bug.zip)

**Comment by mstaniak** [comment]
Thanks, I'll look into this.

**Comment by mstaniak** [comment]
I fixed this bug in the refactoring branch, but code improvements are still in progress. Once I finish, I will merge the changes to master.
The problem was with regular expressions, just like in #21.
