### ISSUE TITLE
Will version 0.5 be published on CRAN?

### ISSUE THREAD

**Issue by FrieseWoudloper** [ModelOriented/localModel#36]
Thank you for this great package! Do you intend to publish the latest version soon on CRAN?
My collegues and I would like to use the new functions, but we cannot install packages from Github because of security policies.

**Comment by pbiecek** [comment]
sorry ot took so long, 
need to fix some issues with maintenance
the v 0.5 is now on CRAN
https://cran.r-project.org/web/packages/localModel/
